apiVersion: apps/v1
kind: Deployment
metadata:
  name: hddcheap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hddcheap
  template:
    metadata:
      name: hddcheap
      labels:
        app: hddcheap
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          image: registry.svc.vesey.tech/will/hddcheap/api
        - name: web
          imagePullPolicy: Always
          image: registry.svc.vesey.tech/will/hddcheap/web

---
apiVersion: v1
kind: Service
metadata:
  name: hddcheap
spec:
  ports:
    - name: tcp
      port: 3000
  selector:
    app: hddcheap

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hddcheap
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`hddcheap.vesey.tech`)
      kind: Rule
      services:
        - name: hddcheap
          port: 3000
  tls:
    certResolver: default
    domains:
      - main: "hddcheap.vesey.tech"

